apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld-techdocs-002
  name: helloworld-techdocs-002
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    app: helloworld-techdocs-002
  type: ClusterIP
